name: Integration Test

on:
  schedule:
    - cron: "0 0 * * 0" # weekly
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO bring back 3.12 for non-git. Should expand the cartesian product ourselves.
        python-version: [3.13, 3.14]
        mopidy-version: [3.3, 3.4] #, "git"]
      # Run all the matrix jobs, even if one fails.
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}-${{ matrix.mopidy-version }}

      - name: Install Mopidy system-wide
        run: |
          sudo apt update
          sudo apt install mopidy libgirepository1.0-dev mpc \
            build-essential python3-dev python3-pip \
            gir1.2-gst-plugins-base-1.0 \
            gir1.2-gstreamer-1.0 \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-tools \
            libcairo2-dev \
            libgirepository-2.0-dev \
            python3-gst-1.0



      - name: Correct mopidy version
        run: |
          if [ ${{ matrix.mopidy-version }} != "git" ]; then
            uv add mopidy==${{ matrix.mopidy-version }}
          else
            uv add "mopidy @ git+https://github.com/mopidy/mopidy.git"
          fi
          uv pip show mopidy
      - name: Install mopidy-tidal
        run: |
          uv sync --group complete

      - name: Integration test
        run: make integration-test
